devices:
- name: TP-7
  sample_rates:
    - 22050
    - 44100
    - 48000
    - 88200
    - 96000
  bit_depths:
    - 8
    - 16
    - 24
  file_types:
    - wav
    - mp3
  bpm_source: :acid_chunk
  unsupported_characters:
    - "™"
    - '"'
  transliterate_paths: true
  uppercase_paths: true

- name: Octatrack
  sample_rates:
    - 44100
  bit_depths:
    - 8
    - 16
    - 24
  file_types:
    - wav
    - aiff
    - aif
  bpm_source: :filename
  bar_multiple: 64
  unsupported_characters:
    - "™"
    - '"'
    - "’"
    - ":"
    - "?"

- name: Playdate
  sample_rates:
    - 44100
  file_types:
    - mp3
  transliterate_metadata: true
