devices:
- name: TP-7
  sample_rates:
    - 44100
    - 48000
    - 88200
    - 96000
  bit_depths:
    - 16
    - 24
  file_types:
    - wav
    - mp3
  bpm_source: :acid_chunk

- name: Octatrack
  sample_rates:
    - 44100
  bit_depths:
    - 16
    - 24
  file_types:
    - wav
    - aiff
    - aif
  bpm_source: :filename
  bar_multiple: 64
