# Minimal stub for taglib-ruby

module TagLib
  module MP4
    class File
      def self.open: [T] (String path) { (File) -> T } -> T
      def tag: () -> untyped
      def save: () -> bool
    end

    class Item
      def self.from_int: (Integer value) -> Item
    end
  end

  module MPEG
    class File
      def self.open: [T] (String path) { (File) -> T } -> T
      def id3v2_tag: (?bool create) -> untyped
      def save: () -> bool
    end
  end

  module RIFF
    module WAV
      class File
        def self.open: [T] (String path) { (File) -> T } -> T
        def id3v2_tag: () -> untyped
      end
    end

    module AIFF
      class File
        def self.open: [T] (String path) { (File) -> T } -> T
        def tag: () -> untyped
        def save: () -> bool
      end
    end
  end

  module ID3v2
    class TextIdentificationFrame
      def initialize: (::String id, untyped encoding) -> void
      def text=: (::String text) -> ::String
    end

    class Tag
      def remove_frames: (::String id) -> void
      def add_frame: (TextIdentificationFrame frame) -> void
      def frame_list: (::String id) -> Array[untyped]
    end
  end

  module String
    UTF8: Integer
  end
end
