name: RuboCop

on:
  push:
    branches: [main]
  pull_request:

jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.1"
      - run: gem install rubocop -v 1.82.1
      - run: rubocop
